# Use a imagem oficial do PHP 8.2 com o Nginx
FROM php:8.2-fpm

# Instale dependências para o Laravel (e PostgreSQL)
RUN apt-get update -qq \
    && apt-get upgrade -qq -y \
    && apt-get install -qq -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libwebp-dev \
        libpng-dev \
        wget \
        libzip-dev \
        nano \
        nginx \
        libpq-dev \
        && docker-php-ext-install gd pdo pdo_pgsql pgsql zip

# Copie os arquivos do Laravel para o container
WORKDIR /app
COPY . .

# Instale as dependências do Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer install --no-interaction --prefer-dist

# Exponha a porta do PHP-FPM
EXPOSE 9000

CMD ["php-fpm"]
